version: "3.3"
services:
  redis:
    extends:
      file: compose-common.yml
      service: redis

  traefik:
    extends:
      file: compose-common.yml
      service: traefik

  api:
    extends:
      file: compose-common.yml
      service: api
    command: python3 -m daphne -b 0.0.0.0 -p 80 app.asgi:application
    depends_on:
      - db
      - traefik
      - redis

  db:
    extends:
      file: compose-common.yml
      service: db

  celery-scheduler:
    extends:
      file: compose-common.yml
      service: celery-scheduler
    entrypoint: []
    depends_on:
      - api

  celery-worker:
    extends:
      file: compose-common.yml
      service: celery-worker
    entrypoint: []
    depends_on:
      - api
    


volumes:
  postgres_data:
  logs:
  cache: