[tool.mypy]
mypy_path = "src"
check_untyped_defs = true
disallow_any_generics = true
ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
no_implicit_reexport = true


[tool.pdm]
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[tool.pdm.scripts]
_.env_file = ".env.dev"
collectstatic.cmd = "python manage.py collectstatic --noinput"
makemigrations.cmd = "python manage.py makemigrations"
migrate.cmd = "python manage.py migrate"


[tool.pdm.dev-dependencies]
dev = [
    "black>=22.1.0",
    "pytest==7.0.1",
    "pytest-django>=4.5.2",
    "mypy>=0.931",
    "django-debug-toolbar>=3.2.4",
    "coverage==6.3.2",
]
[build-system]
requires = ["pdm-pep517>=0.12.0"]
build-backend = "pdm.pep517.api"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE='app.settings.test'
testpaths = [
    "src/",
]
addopts = "--rootdir ./src --disable-warnings"
filterwarnings = 'ignore:function ham\(\) RemovedInDjango40Warning'  # Not Include Django 4.0 Deprecation Warnings

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Leandro de Souza", email = "leandrodesouzadev@gmail.com"},
]
license-expression = "MIT"
dependencies = []
requires-python = ">=3.9"

[project.urls]
Homepage = ""
